### ISSUE TITLE
2.6报这个错误了？

### ISSUE THREAD

**Issue by cxc3214** [ysc/APDPlat#66]
[ERROR] Failed startup of context org.mortbay.jetty.plugin.Jetty6PluginWebAppContext@1a8bcbb{/APDPlat_Web,E:\Workspaces\git\APDPlat\APDPlat_Web\src\main\webapp}
java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: InfoType is not mapped [select o from InfoType o  order by o.id desc]

**Comment by ysc** [comment]
运行项目根目录下的startup.sh脚本，或者将war部署到tomcat-8.0.21，jetty插件现在还不支持java8。
