### ISSUE TITLE
APDPlat2.6运行报错 

### ISSUE THREAD

**Issue by tonyshen277** [ysc/APDPlat#69]
java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: InfoType is not mapped [select o from InfoType o  order by o.id desc]

**Comment by ysc** [comment]
这个错误应该是对项目结构进行变动了吧？
startup.bat脚本中的jetty还不支持JDK8，请运行startup.sh脚本看看有没有问题。
APDPlat2.6使用了JDK8，所以要使用支持JDK8的应用服务器，如：tomcat-8.0.21
