### ISSUE TITLE
javax.servlet.ServletException: File [/platform/include/topnav_apdplat.jsp] not found

### ISSUE THREAD

**Issue by tryrefine** [ysc/APDPlat#70]
就在这两天，获取的master版本。
Eclipse->右键->run as->run on server->tomcat8.0.23（JDK1.8)
登陆成功后，报错如下：
...
SEVERE: Servlet.service() for servlet [jsp] in context with path [/APDPlat_Web] threw exception [javax.servlet.ServletException: File [/platform/include/topnav_apdplat.jsp] not found] with root cause
javax.servlet.ServletException: File [/platform/include/topnav_apdplat.jsp] not found
...

我看了webapp/platform/include这个目录，确实没有topnav_apdplat.jsp文件。
是不是忘了上传这个文件了？
我在常见错误列表中，没有看到这个错误。

杨兄有空了，麻烦看一下，thanks a lot

**Comment by ysc** [comment]
这个文件被打包到了APDPlat_Module的jar包中，在应用启动的时候自动解压释放到对应的目录。这个文件的路径：
https://github.com/ysc/APDPlat/blob/master/APDPlat_Module/src/main/resources/web/platform/include/topnav_apdplat.jsp
你这里出现这个问题不知道是什么原因。
请使用mvn package打包成war，然后复制到tomcat中运行。
顺便说一下，这个项目采用标准的maven构建，出问题一般是开发环境对maven的支持问题，在这个项目开发的时候，是使用Netbeans IDE的，Netbeans应该是对maven支持最早最好的IDE。
