### ISSUE TITLE
自动生成代码的问题

### ISSUE THREAD

**Issue by chenas** [ysc/APDPlat#71]
package org.apdplat.module.infoCollect.homeCollect.basicInfoCollect.action;
import org.apdplat.module.infoCollect.homeCollect.basicInfoCollect.model.BirthControlInfo;
import org.apdplat.platform.action.ExtJSSimpleAction;
import org.apache.struts2.convention.annotation.Namespace;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

@Scope("prototype")
@Controller
@Namespace("/infoCollect/homeCollect/basicInfoCollect")
public class BirthControlInfoAction extends ExtJSSimpleAction<BirthControlInfo> {
}

包含了struts2的东西，奇怪的是我修改了下面两个文件，生成还是不对
/APDPlat_Core/src/main/resources/org/apdplat/platform/action/generator/freemarker/template/action.ftl
/APDPlat_Core/src/main/resources/org/apdplat/platform/action/generator/freemarker/template/action_special.ftl

**Comment by ysc** [comment]
修改文件后，要在APDPlat_Core项目下执行mvn install安装本地依赖。
